- name: configure network interfaces
  template:
    src: templates/hostname.if.j2
    dest: /etc/hostname.{{ item.if }}
    backup: 'True'
    lstrip_blocks: 'True'
    owner: root
    group: wheel
    mode: 0640
  loop:
    "{{ ifaces | flatten }}"
